// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230412193716_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            Paid = false,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 4,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            Paid = false,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 7,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 8,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 9,
                            Paid = false,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 10,
                            Paid = false,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 11,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 12,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 13,
                            Paid = false,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 14,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 15,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 16,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 17,
                            Paid = false,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 18,
                            Paid = true,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 19,
                            Paid = false,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 20,
                            Paid = true,
                            TotalPrice = 0m
                        });
                });

            modelBuilder.Entity("Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EndDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("StartDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDateTime = "7:57 PM",
                            InvoiceId = 1,
                            StartDateTime = "7:37 PM",
                            UserId = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDateTime = "8:07 PM",
                            InvoiceId = 2,
                            StartDateTime = "7:37 PM",
                            UserId = 3,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndDateTime = "8:02 PM",
                            InvoiceId = 3,
                            StartDateTime = "7:37 PM",
                            UserId = 4,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            EndDateTime = "7:52 PM",
                            InvoiceId = 4,
                            StartDateTime = "7:37 PM",
                            UserId = 5,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 5,
                            EndDateTime = "7:47 PM",
                            InvoiceId = 5,
                            StartDateTime = "7:37 PM",
                            UserId = 6,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 6,
                            EndDateTime = "8:07 PM",
                            InvoiceId = 6,
                            StartDateTime = "7:37 PM",
                            UserId = 7,
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 7,
                            EndDateTime = "7:42 PM",
                            InvoiceId = 7,
                            StartDateTime = "7:37 PM",
                            UserId = 2,
                            VehicleId = 7
                        },
                        new
                        {
                            Id = 8,
                            EndDateTime = "7:47 PM",
                            InvoiceId = 8,
                            StartDateTime = "7:37 PM",
                            UserId = 3,
                            VehicleId = 8
                        },
                        new
                        {
                            Id = 9,
                            EndDateTime = "7:52 PM",
                            InvoiceId = 9,
                            StartDateTime = "7:37 PM",
                            UserId = 4,
                            VehicleId = 9
                        },
                        new
                        {
                            Id = 10,
                            EndDateTime = "7:47 PM",
                            InvoiceId = 10,
                            StartDateTime = "7:37 PM",
                            UserId = 5,
                            VehicleId = 10
                        },
                        new
                        {
                            Id = 11,
                            EndDateTime = "7:57 PM",
                            InvoiceId = 11,
                            StartDateTime = "7:37 PM",
                            UserId = 6,
                            VehicleId = 11
                        },
                        new
                        {
                            Id = 12,
                            EndDateTime = "8:07 PM",
                            InvoiceId = 12,
                            StartDateTime = "7:37 PM",
                            UserId = 7,
                            VehicleId = 12
                        },
                        new
                        {
                            Id = 13,
                            EndDateTime = "8:02 PM",
                            InvoiceId = 13,
                            StartDateTime = "7:37 PM",
                            UserId = 2,
                            VehicleId = 13
                        },
                        new
                        {
                            Id = 14,
                            EndDateTime = "7:52 PM",
                            InvoiceId = 14,
                            StartDateTime = "7:37 PM",
                            UserId = 3,
                            VehicleId = 14
                        },
                        new
                        {
                            Id = 15,
                            EndDateTime = "7:42 PM",
                            InvoiceId = 15,
                            StartDateTime = "7:37 PM",
                            UserId = 4,
                            VehicleId = 15
                        },
                        new
                        {
                            Id = 16,
                            EndDateTime = "7:52 PM",
                            InvoiceId = 16,
                            StartDateTime = "7:37 PM",
                            UserId = 5,
                            VehicleId = 16
                        },
                        new
                        {
                            Id = 17,
                            EndDateTime = "8:02 PM",
                            InvoiceId = 17,
                            StartDateTime = "7:37 PM",
                            UserId = 6,
                            VehicleId = 17
                        },
                        new
                        {
                            Id = 18,
                            EndDateTime = "7:57 PM",
                            InvoiceId = 18,
                            StartDateTime = "7:37 PM",
                            UserId = 7,
                            VehicleId = 18
                        },
                        new
                        {
                            Id = 19,
                            EndDateTime = "7:47 PM",
                            InvoiceId = 19,
                            StartDateTime = "7:37 PM",
                            UserId = 2,
                            VehicleId = 19
                        },
                        new
                        {
                            Id = 20,
                            EndDateTime = "8:07 PM",
                            InvoiceId = 20,
                            StartDateTime = "7:37 PM",
                            UserId = 3,
                            VehicleId = 20
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "florinmazureac@gmail.com",
                            Password = "florinmazureac",
                            Role = "Administrator",
                            Username = "Florin Mazureac"
                        },
                        new
                        {
                            Id = 2,
                            Email = "andreiolteanu@gmail.com",
                            Password = "andreiolteanu",
                            Role = "User",
                            Username = "Andrei Olteanu"
                        },
                        new
                        {
                            Id = 3,
                            Email = "adriantabacu@gmail.com",
                            Password = "adriantabacu",
                            Role = "User",
                            Username = "Adrian Tabacu"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mariamanolache@gmail.com",
                            Password = "mariamanolache",
                            Role = "User",
                            Username = "Maria Manolache"
                        },
                        new
                        {
                            Id = 5,
                            Email = "cristinapopescu@gmail.com",
                            Password = "cristinapopescu",
                            Role = "User",
                            Username = "Cristina Popescu"
                        },
                        new
                        {
                            Id = 6,
                            Email = "dorinvoinea@gmail.com",
                            Password = "dorinvoinea",
                            Role = "User",
                            Username = "Dorin Voinea"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mirceaionescu@gmail.com",
                            Password = "mirceaionescu",
                            Role = "User",
                            Username = "Mircea Ionescu"
                        });
                });

            modelBuilder.Entity("Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("RegisterDate")
                        .HasMaxLength(2000)
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4001),
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4003),
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4003),
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4004),
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4005),
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4005),
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4006),
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4006),
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4007),
                            VehicleTypeId = 4
                        },
                        new
                        {
                            Id = 10,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4008),
                            VehicleTypeId = 4
                        },
                        new
                        {
                            Id = 11,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4008),
                            VehicleTypeId = 4
                        },
                        new
                        {
                            Id = 12,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4009),
                            VehicleTypeId = 4
                        },
                        new
                        {
                            Id = 13,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4009),
                            VehicleTypeId = 5
                        },
                        new
                        {
                            Id = 14,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4010),
                            VehicleTypeId = 5
                        },
                        new
                        {
                            Id = 15,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4011),
                            VehicleTypeId = 5
                        },
                        new
                        {
                            Id = 16,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4011),
                            VehicleTypeId = 6
                        },
                        new
                        {
                            Id = 17,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4012),
                            VehicleTypeId = 6
                        },
                        new
                        {
                            Id = 18,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4012),
                            VehicleTypeId = 6
                        },
                        new
                        {
                            Id = 19,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4013),
                            VehicleTypeId = 6
                        },
                        new
                        {
                            Id = 20,
                            RegisterDate = new DateTime(2023, 4, 12, 19, 37, 15, 705, DateTimeKind.Utc).AddTicks(4013),
                            VehicleTypeId = 6
                        });
                });

            modelBuilder.Entity("Entities.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This type of vehicle is represented by a classic bike with several functionalities: quality wheels that absorb vibrations and unevenness of the ground, high-quality steel frame, brakes that allow safe stopping in any situation.",
                            PricePerMinute = 5m,
                            Type = "ClassicBike"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This type of vehicle is represented by a electric bike with several functions: high-quality wheels that absorb vibrations and unevenness of the ground, high-quality steel frame, brakes that allow safe stopping in any situation, the engine that provides the necessary power for any movement and the battery with increased autonomy",
                            PricePerMinute = 10m,
                            Type = "ElectricBike"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This type of vehicle is represented by a classic scooter with several functionalities: weight variation of customers, wheels offer increased driving comfort and iron frame.",
                            PricePerMinute = 15m,
                            Type = "ClassicScooter"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This type of vehicle is represented by an electric scooter with a series of functions: long-lasting battery autonomy, speed that allows moving as quickly as possible to the desired place and wheels offer increased driving comfort.",
                            PricePerMinute = 20m,
                            Type = "ElectricScooter"
                        },
                        new
                        {
                            Id = 5,
                            Description = "This type of vehicle is represented by a classic car with several functionalities: weight variation of customers, wheels offer increased driving comfort and safe in case of anything.",
                            PricePerMinute = 25m,
                            Type = "ClassicCar"
                        },
                        new
                        {
                            Id = 6,
                            Description = "This type of vehicle is represented by an electric car with a series of functions: long-lasting battery autonomy, wheels offer increased driving comfort and protects the environment.",
                            PricePerMinute = 30m,
                            Type = "ElectricCar"
                        });
                });

            modelBuilder.Entity("Entities.Rental", b =>
                {
                    b.HasOne("Entities.Invoice", "Invoice")
                        .WithOne("Rental")
                        .HasForeignKey("Entities.Rental", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Entities.VehicleType", b =>
                {
                    b.HasOne("Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleTypes")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Entities.Invoice", b =>
                {
                    b.Navigation("Rental");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Entities.Vehicle", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("VehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
